[application]

[web.app]

# HTML title tag content
title = "GAIM @ UGA"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
icon = ["assets/icons/favicon.svg"]